
spring:
  profiles:
    active: dev

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.demo.auth.center.entity


security:
  whitelist:
    - /login
    - /error
    - /register