server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://192.168.31.106:3306/auth-dev?useSSL=false&serverTimezone=UTC
    username: root
    password: mysql_JYJnaT
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: INFO
    org.springframework: debug
    org.mybatis: DEBUG
    com.demo.auth.center: DEBUG
